name: env_applicant_task
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - pytest
  - nomkl
  - ipykernel
  - ipywidgets
  - jupyterlab=2.1.1
  - pyarrow=0.17.0
  - python=3.8.2
  - matplotlib